In [27]:
# ============================================================
# IRIS FLOWER CLASSIFICATION - STATISTICAL ANALYSIS
# Member C: Statistical Analysis
# ============================================================

import sys
from pathlib import Path

import pandas as pd
import numpy as np

# ------------------------------------------------------------
# 1. Set project root and load cleaned dataset
# ------------------------------------------------------------

PROJECT_ROOT = Path.cwd().parent
sys.path.append(str(PROJECT_ROOT))

iris_df = pd.read_csv(
    PROJECT_ROOT / "data" / "iris_cleaned.csv"
)

print("=" * 60)
print("IRIS FLOWER CLASSIFICATION - STATISTICAL ANALYSIS")
print("=" * 60)

print("\nCleaned dataset loaded successfully.")

print("\nDataset shape:")
print(iris_df.shape)

print("\nColumns:")
print(iris_df.columns.tolist())

print("\nSpecies:")
print(iris_df["species"].unique())
# ------------------------------------------------------------
# 2. Mean measurements by species
# ------------------------------------------------------------

measurement_columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width"
]

mean_by_species = (
    iris_df
    .groupby("species")[measurement_columns]
    .mean()
    .round(2)
)

print("=" * 60)
print("MEAN MEASUREMENTS BY SPECIES")
print("=" * 60)

display(mean_by_species)
# ------------------------------------------------------------
# 3. Median measurements by species
# ------------------------------------------------------------

median_by_species = (
    iris_df
    .groupby("species")[measurement_columns]
    .median()
    .round(2)
)

print("=" * 60)
print("MEDIAN MEASUREMENTS BY SPECIES")
print("=" * 60)

display(median_by_species)
# ------------------------------------------------------------
# 4. Standard deviation by species
# ------------------------------------------------------------

std_by_species = (
    iris_df
    .groupby("species")[measurement_columns]
    .std()
    .round(2)
)

print("=" * 60)
print("STANDARD DEVIATION BY SPECIES")
print("=" * 60)

display(std_by_species)
# ------------------------------------------------------------
# 5. Minimum and maximum measurements by species
# ------------------------------------------------------------

min_by_species = (
    iris_df
    .groupby("species")[measurement_columns]
    .min()
    .round(2)
)

max_by_species = (
    iris_df
    .groupby("species")[measurement_columns]
    .max()
    .round(2)
)

print("=" * 60)
print("MINIMUM MEASUREMENTS BY SPECIES")
print("=" * 60)

display(min_by_species)

print("=" * 60)
print("MAXIMUM MEASUREMENTS BY SPECIES")
print("=" * 60)

display(max_by_species)
# ------------------------------------------------------------
# 6. Complete statistical summary
# ------------------------------------------------------------

statistical_summary = pd.DataFrame({
    "Mean Sepal Length": mean_by_species["sepal_length"],
    "Mean Sepal Width": mean_by_species["sepal_width"],
    "Mean Petal Length": mean_by_species["petal_length"],
    "Mean Petal Width": mean_by_species["petal_width"],
    "Median Sepal Length": median_by_species["sepal_length"],
    "Median Sepal Width": median_by_species["sepal_width"],
    "Median Petal Length": median_by_species["petal_length"],
    "Median Petal Width": median_by_species["petal_width"]
})

print("=" * 60)
print("COMPLETE STATISTICAL SUMMARY")
print("=" * 60)

display(statistical_summary)
# ------------------------------------------------------------
# 7. Save statistical summary
# ------------------------------------------------------------

output_file = PROJECT_ROOT / "data" / "statistical_summary.csv"

statistical_summary.to_csv(output_file)

print("=" * 60)
print("STATISTICAL SUMMARY SAVED")
print("=" * 60)

print(f"File saved successfully:")
print(output_file)
# ------------------------------------------------------------
# 8. Statistical observations and conclusion
# ------------------------------------------------------------

print("=" * 60)
print("STATISTICAL OBSERVATIONS")
print("=" * 60)

print("""
1. Iris-setosa has the smallest average petal length and petal width.

2. Iris-virginica has the largest average petal length and petal width.

3. Iris-virginica has the largest average sepal length.

4. Iris-setosa has the smallest average sepal length.

5. Petal measurements show clear differences between the three species.

6. Iris-virginica generally has larger measurements than the other species.

7. Iris-setosa shows relatively low variation in petal measurements.

8. Mean and median values are relatively close for most measurements.
""")

print("=" * 60)
print("CONCLUSION")
print("=" * 60)

print("""
The statistical analysis shows clear differences in the
sepal and petal measurements of the three Iris species.

Petal length and petal width show particularly noticeable
differences between the species. These statistical differences
can help distinguish the Iris species and provide a foundation
for the classification model used in the later stages of
the project.
""")

print("=" * 60)
print("MEMBER C STATISTICAL ANALYSIS COMPLETED")
print("=" * 60)

============================================================
IRIS FLOWER CLASSIFICATION - STATISTICAL ANALYSIS
============================================================

Cleaned dataset loaded successfully.

Dataset shape:
(149, 5)

Columns:
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

Species:
<ArrowStringArray>
['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']
Length: 3, dtype: str
============================================================
MEAN MEASUREMENTS BY SPECIES
============================================================

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa              5.01         3.43          1.46         0.25
Iris-versicolor          5.94         2.77          4.26         1.33
Iris-virginica           6.60         2.98          5.56         2.03

============================================================
MEDIAN MEASUREMENTS BY SPECIES
============================================================

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa               5.0          3.4          1.50          0.2
Iris-versicolor           5.9          2.8          4.35          1.3
Iris-virginica            6.5          3.0          5.60          2.0

============================================================
STANDARD DEVIATION BY SPECIES
============================================================

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa              0.35         0.38          0.17         0.11
Iris-versicolor          0.52         0.31          0.47         0.20
Iris-virginica           0.63         0.32          0.55         0.28

============================================================
MINIMUM MEASUREMENTS BY SPECIES
============================================================

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa               4.3          2.3           1.0          0.1
Iris-versicolor           4.9          2.0           3.0          1.0
Iris-virginica            4.9          2.2           4.5          1.4

============================================================
MAXIMUM MEASUREMENTS BY SPECIES
============================================================

                 sepal_length  sepal_width  petal_length  petal_width
species
Iris-setosa               5.8          4.4           1.9          0.6
Iris-versicolor           7.0          3.4           5.1          1.8
Iris-virginica            7.9          3.8           6.9          2.5

============================================================
COMPLETE STATISTICAL SUMMARY
============================================================

                 Mean Sepal Length  Mean Sepal Width  Mean Petal Length  Mean Petal Width  Median Sepal Length  Median Sepal Width  Median Petal Length  Median Petal Width
species
Iris-setosa                   5.01              3.43               1.46              0.25                  5.0                 3.4                 1.50                 0.2
Iris-versicolor               5.94              2.77               4.26              1.33                  5.9                 2.8                 4.35                 1.3
Iris-virginica                6.60              2.98               5.56              2.03                  6.5                 3.0                 5.60                 2.0

============================================================
STATISTICAL SUMMARY SAVED
============================================================
File saved successfully:
c:\Users\jsaan\iris-flower-classification\data\statistical_summary.csv
============================================================
STATISTICAL OBSERVATIONS
============================================================

1. Iris-setosa has the smallest average petal length and petal width.

2. Iris-virginica has the largest average petal length and petal width.

3. Iris-virginica has the largest average sepal length.

4. Iris-setosa has the smallest average sepal length.

5. Petal measurements show clear differences between the three species.

6. Iris-virginica generally has larger measurements than the other species.

7. Iris-setosa shows relatively low variation in petal measurements.

8. Mean and median values are relatively close for most measurements.

============================================================
CONCLUSION
============================================================

The statistical analysis shows clear differences in the
sepal and petal measurements of the three Iris species.

Petal length and petal width show particularly noticeable
differences between the species. These statistical differences
can help distinguish the Iris species and provide a foundation
for the classification model used in the later stages of
the project.

============================================================
MEMBER C STATISTICAL ANALYSIS COMPLETED
============================================================